# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1f1d1db81875c84bad30ed14ec765f391beda5e3d15c87220540c6279f93d4021029fbf1a973683f24dc841817d07ae23ffadbe7deae35a39b80184b1f1d35f

test:
  secret_key_base: 31d8080107dd22db8daa225d4f78c7f3d1479fa3b7e7513e7465e10af57f31df7711731a6529cd30c0ae86b17928df55ad59ffd7c0d670d2071a417f913b406c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
